services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME} 
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME} 
    container_name: paymentgateway
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data